// SHIKO POINT - Season 2026/27 Local Data (Offline Ready)
const SHIKO_DATA = {
  season: "2026/27",
  currency: "£m",
  startingBudget: 100.0,
  maxPlayersPerClub: 3,
  formations: {
    "4-3-3": { DEF: 4, MID: 3, FWD: 3 },
    "4-4-2": { DEF: 4, MID: 4, FWD: 2 },
    "3-5-2": { DEF: 3, MID: 5, FWD: 2 },
    "3-4-3": { DEF: 3, MID: 4, FWD: 3 },
    "4-5-1": { DEF: 4, MID: 5, FWD: 1 }
  },
  positions: ["GK", "DEF", "MID", "FWD"],
  clubs: {
    ARS: { name: "Arsenal", short: "ARS", color: "#EF0107" },
    MCI: { name: "Man City", short: "MCI", color: "#6CABDD" },
    LIV: { name: "Liverpool", short: "LIV", color: "#C8102E" },
    CHE: { name: "Chelsea", short: "CHE", color: "#034694" },
    MUN: { name: "Man United", short: "MUN", color: "#DA291C" },
    TOT: { name: "Tottenham", short: "TOT", color: "#132257" },
    NEW: { name: "Newcastle", short: "NEW", color: "#241F20" },
    AVL: { name: "Aston Villa", short: "AVL", color: "#95BFE5" },
    BHA: { name: "Brighton", short: "BHA", color: "#0057B8" },
    WHU: { name: "West Ham", short: "WHU", color: "#7A263A" },
    FUL: { name: "Fulham", short: "FUL", color: "#000000" },
    BRE: { name: "Brentford", short: "BRE", color: "#E30613" },
    CRY: { name: "Crystal Palace", short: "CRY", color: "#1B458F" },
    BOU: { name: "Bournemouth", short: "BOU", color: "#DA291C" },
    EVE: { name: "Everton", short: "EVE", color: "#003399" },
    NFO: { name: "Nott'm Forest", short: "NFO", color: "#DD0000" },
    WOL: { name: "Wolves", short: "WOL", color: "#FDB913" },
    LEI: { name: "Leicester", short: "LEI", color: "#003090" },
    IPS: { name: "Ipswich", short: "IPS", color: "#0033A0" },
    HUL: { name: "Hull City", short: "HUL", color: "#F5A623" }
  },
  players: [
    { id: 1, name: "David Raya", club: "ARS", pos: "GK", price: 5.5, form: 6.2, goals: 0, assists: 0, cleanSheets: 12, minutes: 2880, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 4.8 },
    { id: 2, name: "Gianluigi Donnarumma", club: "MCI", pos: "GK", price: 5.5, form: 5.8, goals: 0, assists: 0, cleanSheets: 11, minutes: 2700, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 4.5 },
    { id: 3, name: "Alisson", club: "LIV", pos: "GK", price: 5.5, form: 6.0, goals: 0, assists: 1, cleanSheets: 13, minutes: 2970, yellow: 0, red: 0, status: "available", injury: null, expectedPoints: 4.9 },
    { id: 4, name: "Robert Sanchez", club: "CHE", pos: "GK", price: 4.5, form: 4.5, goals: 0, assists: 0, cleanSheets: 8, minutes: 2520, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 3.8 },
    { id: 5, name: "Jordan Pickford", club: "EVE", pos: "GK", price: 4.5, form: 5.2, goals: 0, assists: 0, cleanSheets: 9, minutes: 3060, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 4.1 },
    { id: 6, name: "Emiliano Martinez", club: "AVL", pos: "GK", price: 5.0, form: 5.5, goals: 0, assists: 0, cleanSheets: 10, minutes: 2790, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 4.3 },
    { id: 7, name: "Andre Onana", club: "MUN", pos: "GK", price: 5.0, form: 4.8, goals: 0, assists: 0, cleanSheets: 7, minutes: 2610, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 3.9 },
    { id: 8, name: "Guglielmo Vicario", club: "TOT", pos: "GK", price: 5.0, form: 5.0, goals: 0, assists: 0, cleanSheets: 9, minutes: 2700, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 4.0 },
    { id: 10, name: "William Saliba", club: "ARS", pos: "DEF", price: 6.5, form: 6.8, goals: 2, assists: 1, cleanSheets: 14, minutes: 3060, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 5.6 },
    { id: 11, name: "Gabriel Magalhaes", club: "ARS", pos: "DEF", price: 6.5, form: 7.2, goals: 4, assists: 2, cleanSheets: 13, minutes: 2970, yellow: 5, red: 0, status: "available", injury: null, expectedPoints: 6.1 },
    { id: 12, name: "Virgil van Dijk", club: "LIV", pos: "DEF", price: 6.5, form: 6.5, goals: 3, assists: 1, cleanSheets: 12, minutes: 3150, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 5.4 },
    { id: 13, name: "Ruben Dias", club: "MCI", pos: "DEF", price: 6.0, form: 5.9, goals: 1, assists: 0, cleanSheets: 11, minutes: 2790, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 4.9 },
    { id: 14, name: "Josko Gvardiol", club: "MCI", pos: "DEF", price: 6.0, form: 6.2, goals: 3, assists: 2, cleanSheets: 10, minutes: 2880, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 5.3 },
    { id: 15, name: "Jurrien Timber", club: "ARS", pos: "DEF", price: 5.5, form: 5.8, goals: 1, assists: 3, cleanSheets: 11, minutes: 2700, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 4.8 },
    { id: 16, name: "Reece James", club: "CHE", pos: "DEF", price: 5.5, form: 5.5, goals: 2, assists: 4, cleanSheets: 8, minutes: 2340, yellow: 5, red: 1, status: "available", injury: null, expectedPoints: 4.7 },
    { id: 17, name: "Pedro Porro", club: "TOT", pos: "DEF", price: 5.5, form: 5.7, goals: 2, assists: 5, cleanSheets: 9, minutes: 2880, yellow: 6, red: 0, status: "available", injury: null, expectedPoints: 5.0 },
    { id: 18, name: "Neco Williams", club: "NFO", pos: "DEF", price: 5.0, form: 6.0, goals: 1, assists: 4, cleanSheets: 10, minutes: 2970, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 5.1 },
    { id: 19, name: "James Tarkowski", club: "EVE", pos: "DEF", price: 5.0, form: 5.8, goals: 2, assists: 1, cleanSheets: 9, minutes: 3150, yellow: 7, red: 0, status: "available", injury: null, expectedPoints: 4.9 },
    { id: 20, name: "Marc Guehi", club: "MCI", pos: "DEF", price: 5.5, form: 5.6, goals: 1, assists: 1, cleanSheets: 10, minutes: 2610, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 4.7 },
    { id: 21, name: "Levi Colwill", club: "CHE", pos: "DEF", price: 5.0, form: 5.2, goals: 1, assists: 0, cleanSheets: 7, minutes: 2520, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 4.2 },
    { id: 22, name: "Ezri Konsa", club: "ARS", pos: "DEF", price: 5.0, form: 5.4, goals: 1, assists: 1, cleanSheets: 9, minutes: 2700, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 4.5 },
    { id: 23, name: "Piero Hincapie", club: "ARS", pos: "DEF", price: 5.0, form: 5.3, goals: 0, assists: 2, cleanSheets: 8, minutes: 2340, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 4.3 },
    { id: 24, name: "Ronald Araujo", club: "LIV", pos: "DEF", price: 5.5, form: 5.7, goals: 2, assists: 0, cleanSheets: 9, minutes: 2430, yellow: 5, red: 0, status: "available", injury: null, expectedPoints: 4.8 },
    { id: 25, name: "Daniel Munoz", club: "CRY", pos: "DEF", price: 5.0, form: 5.9, goals: 3, assists: 4, cleanSheets: 8, minutes: 3060, yellow: 8, red: 0, status: "available", injury: null, expectedPoints: 5.2 },
    { id: 26, name: "Matty Cash", club: "AVL", pos: "DEF", price: 4.5, form: 5.1, goals: 2, assists: 3, cleanSheets: 7, minutes: 2700, yellow: 6, red: 0, status: "available", injury: null, expectedPoints: 4.4 },
    { id: 27, name: "Lewis Hall", club: "NEW", pos: "DEF", price: 4.5, form: 4.8, goals: 1, assists: 2, cleanSheets: 6, minutes: 2520, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 4.0 },
    { id: 28, name: "Sven Botman", club: "NEW", pos: "DEF", price: 5.0, form: 5.0, goals: 1, assists: 0, cleanSheets: 8, minutes: 2610, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 4.3 },
    { id: 30, name: "Bruno Fernandes", club: "MUN", pos: "MID", price: 12.0, form: 8.5, goals: 12, assists: 18, cleanSheets: 0, minutes: 3150, yellow: 6, red: 0, status: "available", injury: null, expectedPoints: 7.8 },
    { id: 31, name: "Bukayo Saka", club: "ARS", pos: "MID", price: 10.0, form: 7.8, goals: 14, assists: 12, cleanSheets: 0, minutes: 2970, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 7.2 },
    { id: 32, name: "Declan Rice", club: "ARS", pos: "MID", price: 6.5, form: 6.5, goals: 4, assists: 6, cleanSheets: 0, minutes: 3060, yellow: 5, red: 0, status: "available", injury: null, expectedPoints: 5.5 },
    { id: 33, name: "Dominik Szoboszlai", club: "LIV", pos: "MID", price: 7.5, form: 7.2, goals: 9, assists: 10, cleanSheets: 0, minutes: 2880, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 6.6 },
    { id: 34, name: "Martin Odegaard", club: "ARS", pos: "MID", price: 8.0, form: 6.8, goals: 8, assists: 11, cleanSheets: 0, minutes: 2700, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 6.3 },
    { id: 35, name: "Cole Palmer", club: "CHE", pos: "MID", price: 9.0, form: 6.5, goals: 11, assists: 9, cleanSheets: 0, minutes: 2790, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 6.4 },
    { id: 36, name: "Florian Wirtz", club: "LIV", pos: "MID", price: 8.5, form: 7.0, goals: 10, assists: 12, cleanSheets: 0, minutes: 2610, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 6.8 },
    { id: 37, name: "Jeremy Doku", club: "MCI", pos: "MID", price: 7.5, form: 6.9, goals: 8, assists: 11, cleanSheets: 0, minutes: 2520, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 6.5 },
    { id: 38, name: "Rayan Cherki", club: "MCI", pos: "MID", price: 7.0, form: 6.7, goals: 7, assists: 10, cleanSheets: 0, minutes: 2340, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 6.2 },
    { id: 39, name: "Bruno Guimaraes", club: "ARS", pos: "MID", price: 6.5, form: 6.3, goals: 5, assists: 7, cleanSheets: 0, minutes: 2880, yellow: 7, red: 0, status: "available", injury: null, expectedPoints: 5.6 },
    { id: 40, name: "Moises Caicedo", club: "CHE", pos: "MID", price: 6.0, form: 5.8, goals: 2, assists: 4, cleanSheets: 0, minutes: 2970, yellow: 8, red: 0, status: "available", injury: null, expectedPoints: 4.9 },
    { id: 41, name: "Morgan Gibbs-White", club: "NFO", pos: "MID", price: 7.0, form: 7.5, goals: 11, assists: 13, cleanSheets: 0, minutes: 3060, yellow: 5, red: 0, status: "available", injury: null, expectedPoints: 6.9 },
    { id: 42, name: "Enzo Fernandez", club: "CHE", pos: "MID", price: 6.0, form: 5.6, goals: 4, assists: 6, cleanSheets: 0, minutes: 2700, yellow: 6, red: 0, status: "available", injury: null, expectedPoints: 5.1 },
    { id: 43, name: "Alexis Mac Allister", club: "LIV", pos: "MID", price: 6.0, form: 5.9, goals: 5, assists: 7, cleanSheets: 0, minutes: 2790, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 5.4 },
    { id: 44, name: "Marcus Tavernier", club: "BOU", pos: "MID", price: 5.5, form: 6.2, goals: 7, assists: 8, cleanSheets: 0, minutes: 2880, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 5.7 },
    { id: 45, name: "Iliman Ndiaye", club: "EVE", pos: "MID", price: 5.5, form: 6.0, goals: 8, assists: 6, cleanSheets: 0, minutes: 2700, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 5.5 },
    { id: 46, name: "Eberechi Eze", club: "ARS", pos: "MID", price: 6.5, form: 6.4, goals: 9, assists: 7, cleanSheets: 0, minutes: 2520, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 5.9 },
    { id: 47, name: "Phil Foden", club: "MCI", pos: "MID", price: 7.5, form: 6.0, goals: 8, assists: 8, cleanSheets: 0, minutes: 2340, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 5.8 },
    { id: 48, name: "Kevin De Bruyne", club: "MCI", pos: "MID", price: 8.0, form: 5.5, goals: 5, assists: 9, cleanSheets: 0, minutes: 1800, yellow: 2, red: 0, status: "doubt", injury: "Muscle", expectedPoints: 5.0 },
    { id: 49, name: "Rodri", club: "MCI", pos: "MID", price: 6.5, form: 5.2, goals: 3, assists: 4, cleanSheets: 0, minutes: 2160, yellow: 5, red: 0, status: "available", injury: null, expectedPoints: 4.7 },
    { id: 50, name: "Erling Haaland", club: "MCI", pos: "FWD", price: 15.5, form: 9.2, goals: 28, assists: 5, cleanSheets: 0, minutes: 2970, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 8.5 },
    { id: 51, name: "Alexander Isak", club: "LIV", pos: "FWD", price: 9.5, form: 7.5, goals: 18, assists: 6, cleanSheets: 0, minutes: 2700, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 7.0 },
    { id: 52, name: "Viktor Gyokeres", club: "ARS", pos: "FWD", price: 9.0, form: 7.0, goals: 16, assists: 5, cleanSheets: 0, minutes: 2610, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 6.6 },
    { id: 53, name: "Joao Pedro", club: "CHE", pos: "FWD", price: 8.0, form: 6.8, goals: 14, assists: 7, cleanSheets: 0, minutes: 2790, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 6.3 },
    { id: 54, name: "Ollie Watkins", club: "AVL", pos: "FWD", price: 8.0, form: 6.5, goals: 15, assists: 6, cleanSheets: 0, minutes: 2880, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 6.2 },
    { id: 55, name: "Matheus Cunha", club: "MUN", pos: "FWD", price: 7.5, form: 6.7, goals: 13, assists: 8, cleanSheets: 0, minutes: 2700, yellow: 5, red: 0, status: "available", injury: null, expectedPoints: 6.1 },
    { id: 56, name: "Cody Gakpo", club: "LIV", pos: "FWD", price: 7.0, form: 6.3, goals: 11, assists: 7, cleanSheets: 0, minutes: 2520, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 5.8 },
    { id: 57, name: "Igor Thiago", club: "BRE", pos: "FWD", price: 7.0, form: 6.9, goals: 15, assists: 4, cleanSheets: 0, minutes: 2790, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 6.4 },
    { id: 58, name: "Bryan Mbeumo", club: "MUN", pos: "FWD", price: 7.0, form: 6.4, goals: 12, assists: 6, cleanSheets: 0, minutes: 2880, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 5.9 },
    { id: 59, name: "Antoine Semenyo", club: "MCI", pos: "FWD", price: 7.5, form: 7.1, goals: 14, assists: 8, cleanSheets: 0, minutes: 2610, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 6.7 },
    { id: 60, name: "Kai Havertz", club: "ARS", pos: "FWD", price: 7.0, form: 5.8, goals: 10, assists: 5, cleanSheets: 0, minutes: 2430, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 5.4 },
    { id: 61, name: "Gabriel Martinelli", club: "ARS", pos: "FWD", price: 6.5, form: 5.9, goals: 9, assists: 7, cleanSheets: 0, minutes: 2340, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 5.5 },
    { id: 62, name: "Noni Madueke", club: "ARS", pos: "FWD", price: 6.0, form: 5.7, goals: 8, assists: 6, cleanSheets: 0, minutes: 2160, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 5.2 },
    { id: 63, name: "Nicolas Jackson", club: "CHE", pos: "FWD", price: 6.5, form: 5.5, goals: 11, assists: 4, cleanSheets: 0, minutes: 2520, yellow: 6, red: 0, status: "available", injury: null, expectedPoints: 5.3 },
    { id: 64, name: "Hugo Ekitike", club: "LIV", pos: "FWD", price: 6.0, form: 5.6, goals: 9, assists: 3, cleanSheets: 0, minutes: 1980, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 5.0 },
    { id: 65, name: "Danny Welbeck", club: "CHE", pos: "FWD", price: 5.5, form: 5.2, goals: 8, assists: 3, cleanSheets: 0, minutes: 2160, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 4.7 },
    { id: 70, name: "Illan Meslier", club: "ARS", pos: "GK", price: 4.0, form: 3.5, goals: 0, assists: 0, cleanSheets: 3, minutes: 900, yellow: 0, red: 0, status: "available", injury: null, expectedPoints: 2.8 },
    { id: 71, name: "Ben White", club: "ARS", pos: "DEF", price: 4.5, form: 4.5, goals: 0, assists: 2, cleanSheets: 6, minutes: 1800, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 3.7 },
    { id: 72, name: "Joe Gomez", club: "LIV", pos: "DEF", price: 4.5, form: 4.2, goals: 0, assists: 1, cleanSheets: 5, minutes: 1620, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 3.5 },
    { id: 73, name: "Curtis Jones", club: "LIV", pos: "MID", price: 5.0, form: 4.8, goals: 3, assists: 4, cleanSheets: 0, minutes: 1980, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 4.2 },
    { id: 74, name: "Harvey Elliott", club: "LIV", pos: "MID", price: 5.0, form: 4.9, goals: 4, assists: 5, cleanSheets: 0, minutes: 1800, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 4.4 },
    { id: 75, name: "Ethan Nwaneri", club: "ARS", pos: "MID", price: 4.5, form: 5.0, goals: 5, assists: 3, cleanSheets: 0, minutes: 1440, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 4.3 },
    { id: 76, name: "Liam Delap", club: "CHE", pos: "FWD", price: 5.5, form: 5.3, goals: 7, assists: 2, cleanSheets: 0, minutes: 1620, yellow: 3, red: 0, status: "available", injury: null, expectedPoints: 4.6 },
    { id: 77, name: "Rayan", club: "BOU", pos: "FWD", price: 5.5, form: 5.8, goals: 10, assists: 4, cleanSheets: 0, minutes: 2340, yellow: 2, red: 0, status: "available", injury: null, expectedPoints: 5.3 },
    { id: 78, name: "Chris Wood", club: "NFO", pos: "FWD", price: 6.0, form: 5.9, goals: 12, assists: 2, cleanSheets: 0, minutes: 2610, yellow: 1, red: 0, status: "available", injury: null, expectedPoints: 5.4 },
    { id: 79, name: "Anthony Gordon", club: "NEW", pos: "MID", price: 6.5, form: 5.7, goals: 8, assists: 6, cleanSheets: 0, minutes: 2520, yellow: 4, red: 0, status: "available", injury: null, expectedPoints: 5.3 }
  ],
  fixtures: [
    { gw: 1, home: "ARS", away: "HUL", difficulty: { home: 2, away: 4 } },
    { gw: 1, home: "MCI", away: "BOU", difficulty: { home: 2, away: 4 } },
    { gw: 1, home: "LIV", away: "IPS", difficulty: { home: 2, away: 4 } },
    { gw: 1, home: "CHE", away: "FUL", difficulty: { home: 2, away: 3 } },
    { gw: 1, home: "MUN", away: "LEI", difficulty: { home: 2, away: 3 } },
    { gw: 1, home: "TOT", away: "WOL", difficulty: { home: 2, away: 3 } },
    { gw: 1, home: "NEW", away: "CRY", difficulty: { home: 2, away: 3 } },
    { gw: 1, home: "AVL", away: "EVE", difficulty: { home: 2, away: 3 } },
    { gw: 1, home: "BHA", away: "BRE", difficulty: { home: 2, away: 3 } },
    { gw: 1, home: "NFO", away: "WHU", difficulty: { home: 2, away: 3 } },
    { gw: 2, home: "HUL", away: "MCI", difficulty: { home: 5, away: 2 } },
    { gw: 2, home: "BOU", away: "ARS", difficulty: { home: 4, away: 2 } },
    { gw: 2, home: "IPS", away: "CHE", difficulty: { home: 4, away: 2 } },
    { gw: 2, home: "FUL", away: "LIV", difficulty: { home: 4, away: 2 } },
    { gw: 2, home: "LEI", away: "MUN", difficulty: { home: 4, away: 2 } },
    { gw: 2, home: "WOL", away: "TOT", difficulty: { home: 3, away: 2 } },
    { gw: 2, home: "CRY", away: "NEW", difficulty: { home: 3, away: 2 } },
    { gw: 2, home: "EVE", away: "AVL", difficulty: { home: 3, away: 2 } },
    { gw: 2, home: "BRE", away: "BHA", difficulty: { home: 3, away: 2 } },
    { gw: 2, home: "WHU", away: "NFO", difficulty: { home: 3, away: 2 } }
  ],
  scoring: {
    appearance: 1,
    play60: 1,
    goal: { GK: 10, DEF: 6, MID: 5, FWD: 4 },
    assist: 3,
    cleanSheet: { GK: 4, DEF: 4, MID: 1, FWD: 0 },
    save: 1,
    penaltySave: 5,
    yellow: -1,
    red: -3,
    ownGoal: -2,
    goalsConceded: -1,
    bonus: [3, 2, 1]
  },
  missions: [
    { id: "m1", title: "First XI", desc: "Complete your first team", reward: 5, type: "team" },
    { id: "m2", title: "Captain Success", desc: "Get 15+ points from captain", reward: 10, type: "points" },
    { id: "m3", title: "Smart Transfer", desc: "Make 3 successful transfers", reward: 8, type: "transfers" },
    { id: "m4", title: "Clean Defence", desc: "Get 3 clean sheets in a GW", reward: 12, type: "cs" },
    { id: "m5", title: "Hat-trick Hero", desc: "Your player scores a hat-trick", reward: 15, type: "goals" }
  ],
  achievements: [
    { id: "a1", title: "Beginner", desc: "Create your team", icon: "⚽" },
    { id: "a2", title: "Leader", desc: "Select captain for first time", icon: "©️" },
    { id: "a3", title: "Trader", desc: "Make 10 transfers", icon: "🔄" },
    { id: "a4", title: "Points King", desc: "Score 100 points in a GW", icon: "🔥" },
    { id: "a5", title: "Shiko Master", desc: "Reach level 10", icon: "👑" }
  ]
};
